name: Simple example of using the babashka action

on: [push]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@master
        with:
          babashka-version: 0.2.10

      - name: Do something silly
        run: bb "(mapv str (filter #(.isFile %) (take 5 (file-seq (clojure.java.io/file \".\")))))"
